# -----------------------------------------------------------------------------
# THE ONLY WARNING!!!
# -----------------------------------------------------------------------------

# Do not use tabs in this configuration file! Only SPACES!!!
# This will either lead to parsing errors, or Jekyll will revert to the default settings. Use spaces instead.
# ! Read more: http://jekyllrb.com/docs/configuration/



# -----------------------------------------------------------------------------
# SITE PERSONALIZATION
# -----------------------------------------------------------------------------

name: St. Louis Artworks
# This text will be used on the homepage to personalize the name of your site
# This will also act as a text link that always points to the homepage


# -----------------------------------------------------------------------------
# SEO SETTINGS
# -----------------------------------------------------------------------------

title: Brownerds unite!
# SEO - This will be used for the title text on the homepage

description: St. Louis Artworks provides awesome job training to young St. Louis creatives
# SEO - This will be used for the meta description on the homepage

google_analytics: UA-795125-1
# This will enable Google Analytics to track your site


# -----------------------------------------------------------------------------
# COMMENTS
# -----------------------------------------------------------------------------

disqus: stlartworks
# To enable comments, use your Disqus "shortname" to enable comments
# You can create a free acount here: https://disqus.com/


# -----------------------------------------------------------------------------
# SITE CONFIGURATION
# -----------------------------------------------------------------------------

url: http://stlartworks.github.io
# http://repoName.github.io
# http://www.yourDomainName.com
# This will confiure your sitemap.xml and RSS feed

baseurl: ""
# use this configuraiton for a "Username" or "Organization" site
# ex: http://userName.github.io

# else

# baseurl: "/repoName"
# use this configuraiton for a "Project" site:
# ex: http://userName.github.io/REPO-NAME

timezone: America/Chicago
# Set the timezone. ! Read more: http://jekyllrb.com/docs/configuration/


# -----------------------------------------------------------------------------
# SITE VARIABLES
# -----------------------------------------------------------------------------

# This is a list of variables (Front Matter) to be throughout the site.
# ! Read more: http://jekyllrb.com/docs/frontmatter/

social-media:
    500:
    codepen:
    dribbble: slaw
    email: info@stlartworks.org
    facebook: stlartworks
    flickr:
    github: stlartworks/
    instagram: stlartworks
    linkedin:
    pinterest: stlartworks
    rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
    twitter: stlartworks
    stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
    vimeo:


# -----------------------------------------------------------------------------
# COLLECTIONS
# -----------------------------------------------------------------------------

#  team_members:
#    output: true
#    permalink: /team-members/:path/

# Not everything is a post or a page. Maybe you want to document the various methods in your open source project, members of a team, or talks at a conference. Collections allow you to define a new type of document that behave like Pages or Posts do normally, but also have their own unique properties and namespace.

# Read more: http://jekyllrb.com/docs/collections/

collections:
    board:
        output: true

    instructors:
        output: true

    sponsors:
        output: true

    staff:
        output: true



# -----------------------------------------------------------------------------
# DEFAULT FRONT MATTER SETTINGS
# -----------------------------------------------------------------------------

# Using YAML Front Matter is one way that you can specify configuration in the pages and posts for your site.

# ! Read more: http://jekyllrb.com/docs/configuration/

defaults:
    -
        scope:
          path: "board"
          type: "board"
        values:
          board-title:
          job-title:
          works-for:

          started-board:
          ended-board:

          500:
          dribbble:
          facebook:
          linkedin:
          twitter:

          feature-img:
          quote:


# -----------------------------------------------------------------------------
# PROSE SETTINGS
# -----------------------------------------------------------------------------

# PROSE allows you to manage .md files
# ! Read more: https://github.com/prose/prose/wiki/Prose-Configuration

prose:
  #rooturl: '_posts'
  siteurl: 'http://stlartworks.github.io'
  relativeLinks: 'http://stlartworks.github.io/links.jsonp'
  media: 'images'
  metadata:
    _board:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""


# -----------------------------------------------------------------------------
# Sass SETTINGS
# -----------------------------------------------------------------------------

sass:
  sass_dir: _scss
  # The load path for Sass imports. This folder must only contain imports!
  # Read more: http://jekyllrb.com/docs/assets/

  style: :expanded
    # Sass output settings. ! Read more:
    # http://web-design-weekly.com/2014/06/15/different-sass-output-styles/

    # optoins:
      #:nested
      #:expanded
      #:compact
      #:compressed #minified


# -----------------------------------------------------------------------------
# SAFE PLUGINS allowed by gitHub pages
# -----------------------------------------------------------------------------

gems:
# Plugin list
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  # - jekyll-mentions
  - jekyll-redirect-from


# -----------------------------------------------------------------------------
# PERMALINK SETTINGS
# -----------------------------------------------------------------------------

permalink: /:title/
# These may only apply to posts, not to pages, collections or static files.
# ! Read more: http://jekyllrb.com/docs/permalinks/


# -----------------------------------------------------------------------------
# CONVERSION SETTINGS
# -----------------------------------------------------------------------------

highlighter: pygments
# Pygments is a generic syntax highlighter for general use in all kinds of software such as forum systems, wikis or other applications that need to prettify source code.

# Read more: http://pygments.org/

markdown: kramdown
# kramdown (sic, not Kramdown or KramDown, just kramdown) is a free MIT-licensed Ruby library for parsing and converting a superset of Markdown.

# Read more: http://kramdown.gettalong.org/


# -----------------------------------------------------------------------------
# SAFE MODE
# -----------------------------------------------------------------------------

safe: true
# Use "true" if you intend to let gitHub automatically build your pages

# GitHub Pages is powered by Jekyll, however all Pages sites are generated using the --safe option to disable custom plugins for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.

#You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

# ! Read more: http://jekyllrb.com/docs/plugins/


# -----------------------------------------------------------------------------
# PRODUCITON BUILD SETTINGS
# -----------------------------------------------------------------------------

exclude:
# Exclude (ignore) these files in your Producion build

    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
